spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # 202.196.47.8
    url: jdbc:mysql://localhost:3306/high?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root # 10.133.19.156
    password: 13849063980

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use-sql-comments: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    excluded-view-names:
    template-resolver-order:


server:
  port: 8082
  context-path: /music

#debug: true

logging:
  level: warn
  file: log.txt

save_file_path: C:\Users\Public\Downloads
export_file_path: C:\Users\Public\Downloads
